### ISSUE TITLE
**Good *fn* luck**

### ISSUE THREAD

**Issue by lenrik1589** [anihacc/Ultimacraft-project-public-notice#1]
If you are so confident in the fact that you will be able to make 1.3k mods (well, it's less than that, but still) work together, sure, go ahead and try, no one is here to stop you unless you violate license or something, but, please, *at least fork new versions of the mods you tryna get working together, will ya*?

**Comment by lenrik1589** [comment]
(Also your project name makes me think of a pirate launcher UltimMC)

**Comment by anihacc** [comment]
If you actually read this file, you would see that the entire reason I made it was so that developers that want to raise a licensing issue can contact me. And if you couldn't tell, THESE ARE ALL FORKS! I would never touch the original repositories with any changes I make.

The name is a MAJOR work in progress, and I'll happily accept new name suggestions.
